### ISSUE TITLE
[ENV] - Creating environment using docker

### ISSUE THREAD

**Issue by francisco1code** [FGA-GCES/MSR2021Replication#1]
# Descrition

This question aims to dockeniando the development environment to contain portability between operating systems.

# Tasks

- [x] Create dockerfile
- [x] Create compose
- [x] Automate using makefile
- [x] Update documentation

**Comment by LeonardoPadre** [comment]
# Descrition
Add to docker compose environment for automated testing
# Tasks
- [ ] Create dockerfile
- [ ] Append notebook-test to docker compose
- [ ] Create requirements for tests
