### ISSUE TITLE
[DOC] Generate Sphinx

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [FGA-GCES/MSR2021Replication#8]

**Comment by ArthurFerreiraRodrigues** [comment]
Document fix

**Comment by Madu01** [comment]
## The fix for the bug

The fix for this bug was the addition of the .nojekyll file, this file is empty but it helped the github pages to read the files correctly.

--> for more information about this .nojekyll file, go to [Jekyll](http://blog.virtuacreative.com.br/jekyll-for-beginners-introduction.html)!

**Comment by Madu01** [comment]
### Description:
Put the files in .md in the sphinx document.

### Tasks:
Checklist of tasks that must be performed.

- [x] configure sphinx to accept .md files.
- [ ] comment how to resolve this issue.

### Acceptance criteria:

- [x] Done the tasks defined in the issue

**Comment by Madu01** [comment]
## How to use Markdown in sphinx.

for sphinx to accept `.md` files it was necessary to install a library locally, with the command:

    pip install myst-parser

Then in the `conf.py` file was added:

    extensions = ["myst_parser"]

    source_suffix = {
        '.rst': 'restructuredtext',
        '.txt': 'markdown',
        '.md': 'markdown',
    }

Then I added the markdown files to the project. In `index.rst` file I added the names of markdown files.

--> for more information see: [sphinx-doc-markdown](https://www.sphinx-doc.org/pt_BR/master/usage/configuration.html#general-configuration) and [Using-Markdown-with-Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx)!
